package co.edu.udec.poo.pagodesueldo.vistas.gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import co.edu.udec.poo.pagodesueldo.modelo.crud.ClaseRegistroNominaCRUD;
import co.edu.udec.poo.pagodesueldo.poo.modelo.entidades.ClaseRegistroNomina;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author JOHN
 */
public class ClaseVistaRegistroNomina extends javax.swing.JFrame {
 DefaultTableModel modelo;
    /**
     * Creates new form ClaseVistaRegistroNomina
     */
    public ClaseVistaRegistroNomina() {
        initComponents();
      
    
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        IDCOMPLEMENTOS = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaregistro = new javax.swing.JTable();
        IDNOMINA = new javax.swing.JTextField();
        VALORDEDUCCIDO = new javax.swing.JTextField();
        CEDULA = new javax.swing.JTextField();
        SALARIOBASE = new javax.swing.JTextField();
        TOTALdeducciones = new javax.swing.JTextField();
        IDDEDUCCIONES = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TOTALcomplementos = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Buscar1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SE = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Nomina");
        setSize(new java.awt.Dimension(950, 580));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Id nomina");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Total   ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Total pagado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, 50));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Cedula");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Id deducciones");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Valor deduccido");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1320, 0));
        jPanel1.add(IDCOMPLEMENTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 90, -1));

        tablaregistro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tablaregistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id nomina ", "Cedula", "Id complementos", "Id deducciones", "Id Categoria", "Salario Base", "Total ", "total pago"
            }
        ));
        jScrollPane2.setViewportView(tablaregistro);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 790, 130));
        jPanel1.add(IDNOMINA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 80, -1));
        jPanel1.add(VALORDEDUCCIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 60, -1));
        jPanel1.add(CEDULA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, -1));

        SALARIOBASE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALARIOBASEActionPerformed(evt);
            }
        });
        jPanel1.add(SALARIOBASE, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 100, -1));
        jPanel1.add(TOTALdeducciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 90, -1));
        jPanel1.add(IDDEDUCCIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 90, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Salario base");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Id complementos");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 100, -1));
        jPanel1.add(TOTALcomplementos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 90, -1));

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        nametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nametxtKeyTyped(evt);
            }
        });
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 110, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel4.setText("REGISTRO NOMINA ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        Actualizar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ACTUALIZARSMALL.png"))); // NOI18N
        Actualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ACTUALIZARSMALL.png"))); // NOI18N
        Actualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ACTUALIZARBIG.png"))); // NOI18N
        Actualizar.setSelected(true);
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 100, 60));

        eliminar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARPE.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARPE.png"))); // NOI18N
        eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARBIG.png"))); // NOI18N
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 70, 60));

        Crear.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/CREARSMALL.png"))); // NOI18N
        Crear.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/CREARSMALL.png"))); // NOI18N
        Crear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/Diseño sin título.png"))); // NOI18N
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        jPanel1.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 100, 60));

        Modificar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARPEQUE.png"))); // NOI18N
        Modificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARPEQUE.png"))); // NOI18N
        Modificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARGRANDE.png"))); // NOI18N
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 100, 60));

        Buscar1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/pequebuscar.png"))); // NOI18N
        Buscar1.setText(" ");
        Buscar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/pequebuscar.png"))); // NOI18N
        Buscar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/grandebuscar.png"))); // NOI18N
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 70, 50));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Crear");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Confirmar modificación");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 130, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Eliminar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 90, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Modificar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 90, -1));

        SE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(SE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1060, 590));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Deducciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Complementos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Categorías");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem6.setText("Empleados");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Contratos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Home");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");

        jMenuItem9.setText("C. Sueldo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Transacciones");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ClaseVistaDeducciones visDedu = new ClaseVistaDeducciones();
        visDedu.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ClaseVistaComplementos visComple = new ClaseVistaComplementos();
        visComple.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ClaseVistaCategoria visCate = new ClaseVistaCategoria();
        visCate.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        ClaseVistaEmpleado visEmpleado = new ClaseVistaEmpleado();
        visEmpleado.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        ClaseVistaContratos visContra = new ClaseVistaContratos();
        visContra.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        
        ClaseVistaHome home = new ClaseVistaHome();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        ClaseVistaCalculoSueldo visCalcu = new ClaseVistaCalculoSueldo();
        visCalcu.setVisible(true);
        this.setVisible(false); 
        
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        
        ClaseVistaTransacciones visTransa = new ClaseVistaTransacciones();
        visTransa.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void SALARIOBASEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALARIOBASEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SALARIOBASEActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void nametxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametxtKeyTyped
        char Validar=evt.getKeyChar();
        if (Validar<'0'||Validar>'9')evt.consume(); {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtKeyTyped

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
       
        

    }//GEN-LAST:event_eliminarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
      
    }//GEN-LAST:event_ActualizarActionPerformed

    private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed
       

        // TODO add your handling code here:
    }//GEN-LAST:event_Buscar1ActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
    int k = JOptionPane.showConfirmDialog(null, "Desea registrar al usario ?");
        if (k==0) {
            
        
        ClaseRegistroNominaCRUD objClaseRegistroNominaCRUD = new ClaseRegistroNominaCRUD(); //CONEXION BD
        
        ClaseRegistroNomina oEmpleados = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("");
        
        objClaseRegistroNominaCRUD.ejecutarSentenciaQLS(strSentenciaInsert);
        
        
        mostrarDatos();
        clening ();
        JOptionPane.showMessageDialog(null, "Se agrego con exito!!!");
        }else {
             JOptionPane.showMessageDialog(null, " No se agrego con exito!!!");
        }
        
        
    }//GEN-LAST:event_CrearActionPerformed

      void clening (){
        CEDULA.setText("");
        IDCOMPLEMENTOS.setText("");
        IDDEDUCCIONES.setText("");
     IDNOMINA.setText(" ");
        SALARIOBASE.setText("");
        TOTALcomplementos.setText("");
       TOTALdeducciones .setText("");
      }
       public void mostrarDatos(){
        
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        
        ClaseRegistroNominaCRUD objClaseEmpleadoCRUD = new ClaseRegistroNominaCRUD(); //CONEXION BD
        
        try {
            ResultSet resultado = objClaseEmpleadoCRUD.consultarRegistros("SELECT * FROM EMPLEADOS");
            
            while (resultado.next()) {
                //System.out.println(resultado.getString("ID"));
                System.out.println(resultado.getString("E"));
                System.out.println(resultado.getString("EMP_APELLIDO"));
                System.out.println(resultado.getString("NUM_CEDULA"));
                System.out.println(resultado.getString("EMP_DIRECCION"));
                System.out.println(resultado.getString("TELEFONO"));
                System.out.println(resultado.getString("COD_CATEGORIA"));
                System.out.println(resultado.getString("NUM_CUENTA"));
                System.out.println(resultado.getString("NUM_CONTRATO"));
                
                Object[] oUsuario={resultado.getString("EMP_NOMBRE"),resultado.getString("EMP_APELLIDO"),resultado.getString("NUM_CEDULA"),resultado.getString("EMP_DIRECCION"),resultado.getString("TELEFONO"),resultado.getString("COD_CATEGORIA"),resultado.getString("NUM_CUENTA"),resultado.getString("NUM_CONTRATO")};
                
                modelo.addRow(oUsuario);
                
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    public ClaseRegistroNomina recuperarDatosGUI(){
        ClaseRegistroNomina oEmpleados = new ClaseRegistroNomina();
        
         oEmpleados.setCedula(Integer.parseInt(CEDULA.getText()));
         oEmpleados.setIdComplemento(Integer.parseInt(IDCOMPLEMENTOS.getText()));
          oEmpleados.setIdDeducciones(Integer.parseInt(IDDEDUCCIONES.getText()));
         oEmpleados.setIdNomina(Integer.parseInt(IDNOMINA.getText()));
         oEmpleados.setSalarioBase(Integer.parseInt(SALARIOBASE.getText()));
      
         oEmpleados.setTotalComplementos(Integer.parseInt(TOTALcomplementos.getText()));
         oEmpleados.setTotalDeducciones(Integer.parseInt(TOTALdeducciones.getText()));
      
         
         return oEmpleados; }
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        
        
    }//GEN-LAST:event_ModificarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaRegistroNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaRegistroNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaRegistroNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaRegistroNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaseVistaRegistroNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Buscar1;
    private javax.swing.JTextField CEDULA;
    private javax.swing.JButton Crear;
    private javax.swing.JTextField IDCOMPLEMENTOS;
    private javax.swing.JTextField IDDEDUCCIONES;
    private javax.swing.JTextField IDNOMINA;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField SALARIOBASE;
    private javax.swing.JLabel SE;
    private javax.swing.JTextField TOTALcomplementos;
    private javax.swing.JTextField TOTALdeducciones;
    private javax.swing.JTextField VALORDEDUCCIDO;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTable tablaregistro;
    // End of variables declaration//GEN-END:variables
}
