/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udec.poo.pagodesueldo.vistas.gui;


import co.edu.udec.poo.pagodesueldo.modelo.crud.ClaseCategoriaCRUD;
import co.edu.udec.poo.pagodesueldo.modelo.crud.ClaseDeduccionesCRUD;
import co.edu.udec.poo.pagodesueldo.poo.modelo.entidades.ClaseDeducciones;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author JARK
 */
public class ClaseVistaDeducciones extends javax.swing.JFrame {
DefaultTableModel modelDeducciones; 
    /**
     * Creates new form ClaseVistaDeducciones
     */
    public ClaseVistaDeducciones() {
        initComponents();
        String[] titulos = {"id deducciones", "Nombre", "Porcentaje", "RangoInicial", "RangoFinal"};

        modelDeducciones = new DefaultTableModel(null, titulos);
        tablaDeducciones.setModel(modelDeducciones);
     
    }
    
    public ClaseDeducciones recuperardatos() {
        ClaseDeducciones clasededucciones = new ClaseDeducciones();
        int Iddeducciones = Textid.getText().isEmpty() ? 0 : Integer.parseInt(Textid.getText());
        clasededucciones.setIdDeduccion(Iddeducciones);
        clasededucciones.setNombre(textnombre.getText());
        clasededucciones.setPorcentajeDedu(Integer.parseInt(textporcentaje.getText()));
        clasededucciones.setValorRangoInicial(Integer.parseInt(Textrangoinicial.getText()));

        clasededucciones.setValorRangoFinal(Integer.parseInt(textrangofinal.getText()));
        return clasededucciones;

    }
    
    
    
    
    void clening (){
      Textid.setText("");
        textnombre.setText("");
        textporcentaje.setText("");
         Textrangoinicial.setText("");
       textrangofinal.setText("");
       
    }

     public int variableSeleccion(){
        int variable = tablaDeducciones.getSelectedRow();
        
        
        return variable;
    }
    
     
       
  public  void limpiar (){
    
    this.Textid.setText("");
    this.textnombre.setText("");
     this.textporcentaje.setText("");
    this.Textrangoinicial.setText("");
    this.textrangofinal.setText("");
   
    
    Crear.setEnabled(true);
   Modificar.setEnabled(false);
    Eliminar.setEnabled(false);
  
}

    
    
    



        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDeducciones = new javax.swing.JTable();
        Textid = new javax.swing.JTextField();
        textnombre = new javax.swing.JTextField();
        Textrangoinicial = new javax.swing.JTextField();
        textrangofinal = new javax.swing.JTextField();
        textporcentaje = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Crear = new javax.swing.JButton();
        Buscar1 = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SE = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu10.setText("jMenu10");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deducciones");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Rango final");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Porcentaje ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Id deducciones");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1320, 0));

        tablaDeducciones.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tablaDeducciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id deducciones", "Nombre", "Porcentaje", "Rango inicial", "Rango final"
            }
        ));
        tablaDeducciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDeduccionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaDeducciones);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 730, 110));

        Textid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextidKeyTyped(evt);
            }
        });
        jPanel1.add(Textid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, -1));

        textnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textnombreKeyTyped(evt);
            }
        });
        jPanel1.add(textnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 120, -1));

        Textrangoinicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextrangoinicialKeyTyped(evt);
            }
        });
        jPanel1.add(Textrangoinicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 160, -1));

        textrangofinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textrangofinalKeyTyped(evt);
            }
        });
        jPanel1.add(textrangofinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, -1));

        textporcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textporcentajeKeyTyped(evt);
            }
        });
        jPanel1.add(textporcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 120, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Rango Inicial");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        Eliminar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARPE.png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setMaximumSize(new java.awt.Dimension(100, 100));
        Eliminar.setMinimumSize(new java.awt.Dimension(50, 50));
        Eliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARPE.png"))); // NOI18N
        Eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARBIG.png"))); // NOI18N
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 70, 60));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 110, 30));

        Crear.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/CREARSMALL.png"))); // NOI18N
        Crear.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/CREARSMALL.png"))); // NOI18N
        Crear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/Diseño sin título.png"))); // NOI18N
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        jPanel1.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 100, 60));

        Buscar1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/pequebuscar.png"))); // NOI18N
        Buscar1.setText(" ");
        Buscar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/pequebuscar.png"))); // NOI18N
        Buscar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/grandebuscar.png"))); // NOI18N
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 70, 50));

        Modificar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARPEQUE.png"))); // NOI18N
        Modificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARPEQUE.png"))); // NOI18N
        Modificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARGRANDE.png"))); // NOI18N
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 100, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel4.setText("DEDUCCIONES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Crear");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 90, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Eliminar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 90, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Modificar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 90, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1060, 590));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1060, 590));

        SE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(SE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1060, 590));

        jMenu3.setText("Menu");

        jMenuItem1.setText("Empleados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem3.setText("R Nomina");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Categorías");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem6.setText("Complementos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem8.setText("Contratos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Home");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Procesos");

        jMenuItem10.setText("C. Sueldo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Transacciones");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

        int k = JOptionPane.showConfirmDialog(null, "desea eliminar  ");
        if (k==0) {                  JOptionPane.showMessageDialog(null, " se elimino correctamente");
        
        
        ClaseDeduccionesCRUD conexión = new ClaseDeduccionesCRUD();
        ClaseDeducciones clasededucciones = recuperardatos();
        String strSentenciaInsert = String.format("DELETE FROM  TabDeducciones WHERE iddeducciones=%d", clasededucciones.getIdDeduccion());
        conexión.ejecuarsentencia(strSentenciaInsert);

        this.mostrardatos();
        }
        else   {
            JOptionPane.showMessageDialog(null, " No elimino correctamente");
        }
              
    }//GEN-LAST:event_EliminarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ClaseVistaEmpleado visEmpleado = new ClaseVistaEmpleado();
        visEmpleado.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ClaseVistaRegistroNomina visNomina = new ClaseVistaRegistroNomina();
        visNomina.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ClaseVistaCategoria visCate = new ClaseVistaCategoria();
        visCate.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        ClaseVistaCalculoSueldo visCalcu = new ClaseVistaCalculoSueldo();
        visCalcu.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        ClaseVistaTransacciones visTransa = new ClaseVistaTransacciones();
        visTransa.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        ClaseVistaComplementos visComple = new ClaseVistaComplementos();
        visComple.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        ClaseVistaContratos visContra = new ClaseVistaContratos();
        visContra.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        ClaseVistaHome home = new ClaseVistaHome();
        home.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed
    
    private void TextidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextidKeyTyped
      
char Validar=evt.getKeyChar();
        if (Validar<'0'||Validar>'9')evt.consume(); {
            
        }          
    }//GEN-LAST:event_TextidKeyTyped

    private void textporcentajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textporcentajeKeyTyped

char Validar=evt.getKeyChar();
        if (Validar<'0'||Validar>'9')evt.consume(); {
            
                 // TODO add your handling code here:
    }             // TODO add your handling code here:
    }//GEN-LAST:event_textporcentajeKeyTyped

    private void TextrangoinicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextrangoinicialKeyTyped
       
char Validar=evt.getKeyChar();
        if (Validar<'0'||Validar>'9')evt.consume(); {
            
                  // TODO add your handling code here:
    }      // TODO add your handling code here:
    }//GEN-LAST:event_TextrangoinicialKeyTyped

    private void textrangofinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textrangofinalKeyTyped

char Validar=evt.getKeyChar();
        if (Validar<'0'||Validar>'9')evt.consume(); {
          
                 // TODO add your handling code here:
    }             // TODO add your handling code here:
    }//GEN-LAST:event_textrangofinalKeyTyped

    private void textnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textnombreKeyTyped

        char Name=evt.getKeyChar();
                if ((Name < 'a' || Name > 'z') && (Name < 'A' || Name > 'Z')) {
    evt.consume();
    JOptionPane.showMessageDialog(null, "Solo puede ingresar letras");
}        // TODO add your handling code here:
    }//GEN-LAST:event_textnombreKeyTyped

    private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed

        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_Buscar1ActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
       int k = JOptionPane.showConfirmDialog(null, "dese  crear");
        if (k==0) {
        
        ClaseDeduccionesCRUD conexión = new ClaseDeduccionesCRUD(); 
          ClaseDeducciones claseDeducciones= recuperardatos();         
   String strSentenciaInsert = String.format("INSERT INTO TabDeducciones(Nombred, Porcentaje, RangoInicial, RangoFinal)VALUES('%s','%s','%s','%s')", claseDeducciones.getNombre(), claseDeducciones.getPorcentajeDedu(), claseDeducciones.getValorRangoInicial(), claseDeducciones.getValorRangoFinal());
           
   conexión.ejecuarsentencia(strSentenciaInsert);  
        this.mostrardatos();
        this.limpiar();
                  JOptionPane.showMessageDialog(null, "se agrego correctamente");

        } else{
                              JOptionPane.showMessageDialog(null, "No se agrego correctamente");

        }
    }//GEN-LAST:event_CrearActionPerformed
    
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed

        int k = JOptionPane.showConfirmDialog(null, "desea modificar  ");
        if (k==0) {                  JOptionPane.showMessageDialog(null, " se modficar correctamente");
        
        ClaseDeduccionesCRUD conexión = new ClaseDeduccionesCRUD();
        ClaseDeducciones claseDeducciones = recuperardatos();

        String strSentenciaInsert = String.format("UPDATE TabDeducciones SET Nombred='%s',Porcentaje='%s', RangoInicial ='%s', RangoFinal ='%s' WHERE iddeducciones='%d'",
                claseDeducciones.getNombre(), claseDeducciones.getPorcentajeDedu(), claseDeducciones.getValorRangoInicial(), claseDeducciones.getValorRangoFinal(), claseDeducciones.getIdDeduccion());

        conexión.ejecuarsentencia(strSentenciaInsert);

        this.mostrardatos();

        this.limpiar();
        }else  JOptionPane.showMessageDialog(null, "  No se modficar correctamente");
            
    
    }//GEN-LAST:event_ModificarActionPerformed

    private void tablaDeduccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDeduccionesMouseClicked
        // TODO add your handling code here:
        
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            Textid.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());

            textnombre.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            textporcentaje.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());

            Textrangoinicial.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());

            textrangofinal.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
        }

        Crear.setEnabled(true);
        Eliminar.setEnabled(true);
        Modificar.setEnabled(true);
        
        
        
        
        
        
        
    }//GEN-LAST:event_tablaDeduccionesMouseClicked

    
        public void mostrardatos() {
        while (modelDeducciones.getRowCount() > 0) {
            modelDeducciones.removeRow(0);
        }
        ClaseDeduccionesCRUD conexión = new ClaseDeduccionesCRUD();
        try {
            ResultSet resultado = conexión.consultardato("SELECT*FROM TabDeducciones");
            while (resultado.next()) {
                System.out.println(resultado.getString("iddeducciones"));

                System.out.println(resultado.getString("Nombred"));
                System.out.println(resultado.getString("Porcentaje"));
                System.out.println(resultado.getString("RangoInicial"));
                System.out.println(resultado.getString("RangoFinal"));
                Object[] oUsuario = {resultado.getString("iddeducciones"), resultado.getString("Nombred"), resultado.getString("Porcentaje"), resultado.getString("RangoInicial"), resultado.getString("RangoFinal")};
                modelDeducciones.addRow(oUsuario);
            }
        } catch (Exception e) {
            System.out.println(e);

        }
    }
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaDeducciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaDeducciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaDeducciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaDeducciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaseVistaDeducciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar1;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel SE;
    private javax.swing.JTextField Textid;
    private javax.swing.JTextField Textrangoinicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaDeducciones;
    private javax.swing.JTextField textnombre;
    private javax.swing.JTextField textporcentaje;
    private javax.swing.JTextField textrangofinal;
    // End of variables declaration//GEN-END:variables
}
