/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udec.poo.pagodesueldo.vistas.gui;


import co.edu.udec.poo.pagodesueldo.modelo.crud.ClaseContratoCRUD;
import co.edu.udec.poo.pagodesueldo.poo.modelo.entidades.ClaseContrato;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author JARK
 */
public class ClaseVistaContratos extends javax.swing.JFrame {
DefaultTableModel modelcontrato; 
    /**
     * Creates new form ClaseVistaContratos
     */
    public ClaseVistaContratos() {
        initComponents();
      String [] titulos = {"No.contrato", "Fecha de alta", 
          "Fecha de baja", "Puesto de trabajo", }; 
        
        modelcontrato = new DefaultTableModel(null,titulos);
        tablacontratos.setModel(modelcontrato);
        
    }
    
     public ClaseContrato recuperardatos(){
     ClaseContrato claseContrato = new ClaseContrato();
     int NuContrato = Nocontrato.getText().isEmpty()?0: Integer.parseInt(Nocontrato.getText());
    
     claseContrato.setNuContrato(NuContrato);
     
      claseContrato.setFechaAlta(fechadealta.getText());
       claseContrato.setFechaBaja(fechadebaja.getText());
  claseContrato.setPuestoTrabajo(Puesto.getText());
     return claseContrato;
 }
public void mostrardatos () {
     while (modelcontrato.getRowCount()> 0){
      modelcontrato.removeRow(0);
     } 
 ClaseContratoCRUD conexión = new ClaseContratoCRUD(); 
      try {
            ResultSet resultado = conexión.consultardato("SELECT*FROM TABCONTRATO"); 
            while (resultado.next()) {
            System.out.println(resultado.getString("NoContrato"));  
                 
                System.out.println(resultado.getString("Fechalta"));  
                System.out.println(resultado.getString("FechaBaja")) ; 
                 System.out.println(resultado.getString("PuestoTrabajo")) ;
                  Object [] oUsuario = {resultado.getString("NoContrato"), resultado.getString("Fechalta"), resultado.getString("FechaBaja"),  resultado.getString("PuestoTrabajo")};
   modelcontrato.addRow(oUsuario);
            }
        } catch (Exception e) {
            System.out.println(e);  
               
        } }
   
  public  void limpiar (){
    
    this.Nocontrato.setText("");
    this.fechadealta.setText("");
    this.fechadebaja.setText("");
    this.Puesto.setText("");
    Crear.setEnabled(true);
   Modificar.setEnabled(false);
    eliminar.setEnabled(false);
  
        
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacontratos = new javax.swing.JTable();
        Puesto = new javax.swing.JTextField();
        fechadealta = new javax.swing.JTextField();
        fechadebaja = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        Nocontrato = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Buscar1 = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SE = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contratos");
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(950, 580));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 580));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Fecha de alta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Fecha de baja");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("No. Contrato");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1320, 0));

        tablacontratos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tablacontratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. contrato", "Fecha de alta", "Fecha de baja", "Puesto de trabajo"
            }
        ));
        tablacontratos.setToolTipText("");
        tablacontratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacontratosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablacontratos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 750, 100));

        Puesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PuestoKeyTyped(evt);
            }
        });
        jPanel1.add(Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, -1));

        fechadealta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechadealtaActionPerformed(evt);
            }
        });
        fechadealta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechadealtaKeyTyped(evt);
            }
        });
        jPanel1.add(fechadealta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 120, -1));

        fechadebaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechadebajaKeyTyped(evt);
            }
        });
        jPanel1.add(fechadebaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 120, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Puesto de Trabajo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        eliminar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARPE.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARPE.png"))); // NOI18N
        eliminar.setRequestFocusEnabled(false);
        eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARBIG.png"))); // NOI18N
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 80, 50));

        Nocontrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NocontratoKeyTyped(evt);
            }
        });
        jPanel1.add(Nocontrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, -1));

        Cancelar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ACTUALIZARSMALL.png"))); // NOI18N
        Cancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ACTUALIZARSMALL.png"))); // NOI18N
        Cancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ACTUALIZARBIG.png"))); // NOI18N
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 100, 60));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 140, 30));

        Buscar1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/pequebuscar.png"))); // NOI18N
        Buscar1.setText(" ");
        Buscar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/pequebuscar.png"))); // NOI18N
        Buscar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/grandebuscar.png"))); // NOI18N
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 70, 50));

        Crear.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/CREARSMALL.png"))); // NOI18N
        Crear.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/CREARSMALL.png"))); // NOI18N
        Crear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/Diseño sin título.png"))); // NOI18N
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        jPanel1.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 100, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel4.setText("CONTRATOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        Modificar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARPEQUE.png"))); // NOI18N
        Modificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARPEQUE.png"))); // NOI18N
        Modificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARGRANDE.png"))); // NOI18N
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 100, 60));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Crear");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Cancelar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 130, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Eliminar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 90, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Modificar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 90, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1060, 590));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Eliminar");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 90, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1060, 550));

        SE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(SE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1060, 590));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Deducciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Complementos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Categorías");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("R Nomina");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Empleados");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem8.setText("Home");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");

        jMenuItem9.setText("C. Sueldos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Transacciones");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
int k = JOptionPane.showConfirmDialog(null, "desea eliminar  ");
        if (k==0) {                  JOptionPane.showMessageDialog(null, " se elimino correctamente"); 
        ClaseContratoCRUD conexión = new ClaseContratoCRUD(); 
          ClaseContrato claseContrato = recuperardatos();
        String strSentenciaInsert = String.format("DELETE FROM  TABCONTRATO WHERE NoContrato=%d",claseContrato.getNuContrato());
   conexión.ejecuarsentencia(strSentenciaInsert);  
      
       this.mostrardatos();       
       }
        else   {
            JOptionPane.showMessageDialog(null, " No elimino correctamente");
        }    
    }//GEN-LAST:event_eliminarActionPerformed
    
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        ClaseVistaHome home = new ClaseVistaHome();
        home.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        ClaseVistaEmpleado visEmpleado = new ClaseVistaEmpleado();
        visEmpleado.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ClaseVistaRegistroNomina visNomina = new ClaseVistaRegistroNomina();
        visNomina.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ClaseVistaCategoria visCate = new ClaseVistaCategoria();
        visCate.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ClaseVistaComplementos visComple = new ClaseVistaComplementos();
        visComple.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ClaseVistaDeducciones visDedu = new ClaseVistaDeducciones();
        visDedu.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        ClaseVistaCalculoSueldo visCalcu = new ClaseVistaCalculoSueldo();
        visCalcu.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        ClaseVistaTransacciones visTransa = new ClaseVistaTransacciones();
        visTransa.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed

        limpiar(); 
JOptionPane.showMessageDialog(null, "Se elimino correctamente");

        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed
   
    private void NocontratoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NocontratoKeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_NocontratoKeyTyped

    private void fechadealtaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechadealtaKeyTyped


        // TODO add your handling code here:
    }//GEN-LAST:event_fechadealtaKeyTyped

    private void fechadebajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechadebajaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fechadebajaKeyTyped

    private void PuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PuestoKeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_PuestoKeyTyped

    private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_Buscar1ActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
int k = JOptionPane.showConfirmDialog(null, "dese  crear");
        if (k==0) { JOptionPane.showMessageDialog(null, "se agrego correctamente");

        
        ClaseContratoCRUD conexión = new ClaseContratoCRUD(); 
          ClaseContrato claseContrato = recuperardatos();         
   String strSentenciaInsert = String.format("INSERT INTO TABCONTRATO(NoContrato,Fechalta,FechaBaja,PuestoTrabajo)"
           + "VALUES(null,'%s','%s','%s')", claseContrato.getFechaAlta(), claseContrato.getFechaBaja(), claseContrato.getPuestoTrabajo());
           
   conexión.ejecuarsentencia(strSentenciaInsert);  
        this.mostrardatos();
        this.limpiar();
        }    
  else{
                              JOptionPane.showMessageDialog(null, "No se agrego correctamente");

        }
        
   
    }//GEN-LAST:event_CrearActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
int k = JOptionPane.showConfirmDialog(null, "desea modificar  ");
        if (k==0) {                  JOptionPane.showMessageDialog(null, " se modificar correctamente"); 
        
     ClaseContratoCRUD conexión = new ClaseContratoCRUD();
ClaseContrato claseContrato = recuperardatos();

   String strSentenciaInsert = String.format("UPDATE TABCONTRATO SET Fechalta='%s',  fechaBaja='%s', PuestoTrabajo ='%s' WHERE NoContrato='%d'", claseContrato.getFechaAlta() ,claseContrato.getFechaBaja(), claseContrato.getPuestoTrabajo(), claseContrato.getNuContrato());
   
   conexión.ejecuarsentencia(strSentenciaInsert);  
   
   
   
         this.mostrardatos();

       this.limpiar();    
       }else  JOptionPane.showMessageDialog(null, "  No se modficar correctamente");
            
        {
    
    }
    
//         String strSentenciaUpdate = String.format("UPDATE EMPLEADOS SET EMP_NOMBRE='%s',EMP_APELLIDO='%s',TELEFONO='%s',NUM_CUENTA='%s',EMP_DIRECCION='%s',COD_CATEGORIA='%s',NUM_CONTRATO='%s' WHERE NUM_CEDULA='%d'",oEmpleados.getEMP_NOMBRE(),oEmpleados.getEMP_APELLIDO(),oEmpleados.getTELEFONO(),oEmpleados.getNUM_CUENTA(),oEmpleados.getEMP_DIRECCION(),oEmpleados.getCOD_CATEGORIA(),oEmpleados.getNUM_CONTRATO(),oEmpleados.getNUM_CEDULA());
//        
//        objClaseEmpleadoCRUD.ejecutarSentenciaQLS(strSentenciaUpdate);
//        
        
        
        
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void fechadealtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechadealtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechadealtaActionPerformed

    private void tablacontratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacontratosMouseClicked

if(evt.getClickCount()==1){
    JTable receptor = (JTable)evt.getSource();
    Nocontrato.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
   
   fechadealta.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
    fechadebaja.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());

 Puesto.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
}

   Crear.setEnabled(true);
    eliminar.setEnabled(true);
    Modificar.setEnabled(true);




        // TODO add your handling code here:
    }//GEN-LAST:event_tablacontratosMouseClicked

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
       /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaseVistaContratos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar1;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nocontrato;
    private javax.swing.JTextField Puesto;
    private javax.swing.JLabel SE;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fechadealta;
    private javax.swing.JTextField fechadebaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablacontratos;
    // End of variables declaration//GEN-END:variables

  

}
