/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udec.poo.pagodesueldo.vistas.gui;
import co.edu.udec.poo.pagodesueldo.modelo.crud.ClaseCategoriaCRUD;
import co.edu.udec.poo.pagodesueldo.poo.modelo.entidades.ClaseCategoria;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author JARK
 */
public class ClaseVistaCategoria extends javax.swing.JFrame {
 
/**
     * Creates new form ClaseVistaCategoria
     */
    DefaultTableModel modelo;
    
    public ClaseVistaCategoria() {
                initComponents();
                ClaseCategoriaCRUD categoriaCRUD =new ClaseCategoriaCRUD();
                
                String[] titulos={"CODIGO", "NOMBRE", "SUELDO"};
                modelo = new DefaultTableModel(null,titulos);

                tblCategoria.setModel(modelo);
               this.mostrarDatos();
     
    }
    
    
    void clening (){
      txtCodigo.setText("");
        txtNombre.setText("");
        txtSueldo.setText("");
       
    }

    


        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCategoria = new javax.swing.JTable();
        Modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Categorias");
        setSize(new java.awt.Dimension(950, 580));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nombre categoría");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Codigo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1320, 0));

        tblCategoria.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id categoría", "Nombre categoría", "Sueldo base"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCategoria);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 660, 100));

        Modificar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARPEQUE.png"))); // NOI18N
        Modificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARPEQUE.png"))); // NOI18N
        Modificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARGRANDE.png"))); // NOI18N
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 100, 60));

        eliminar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARPE.png"))); // NOI18N
        eliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARPE.png"))); // NOI18N
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 100, 60));

        Crear.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/CREARSMALL.png"))); // NOI18N
        Crear.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/CREARSMALL.png"))); // NOI18N
        Crear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/Diseño sin título.png"))); // NOI18N
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        jPanel1.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 100, 60));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Sueldo ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 100, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, -1));

        txtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoKeyTyped(evt);
            }
        });
        jPanel1.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 150, -1));

        Buscar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/pequebuscar.png"))); // NOI18N
        Buscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/pequebuscar.png"))); // NOI18N
        Buscar.setRequestFocusEnabled(false);
        Buscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/grandebuscar.png"))); // NOI18N
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 100, 60));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 160, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel4.setText("CATEGORIAS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Crear");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 90, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Eliminar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 90, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Modificar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 90, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1060, 590));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1060, 590));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Deducciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Complementos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Contratos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("R Nomina");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Empleados");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem8.setText("Home");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");

        jMenuItem9.setText("C. Sueldo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem2.setText("Transacciones");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
        
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
int k = JOptionPane.showConfirmDialog(null, "desea modificar  ");
        if (k==0) {                  JOptionPane.showMessageDialog(null, " se modficar correctamente"); 
        ClaseCategoriaCRUD objClaseEmpleadoCRUD = new ClaseCategoriaCRUD(); //CONEXION BD
        
        ClaseCategoria oCategoria = recuperarDatosGUI();
        
        String strSentenciaUpdate = String.format("UPDATE TABCATEGORIA SET CODIGO_CATE='%s',NOMBRE='%s',SUELDO='%s' WHERE CODIGO_CATE = '%d'",oCategoria.getCODIGO(), oCategoria.getNOMBRE(), oCategoria.getSUELDO(),oCategoria.getCODIGO());
        
        objClaseEmpleadoCRUD.ejecutarSentenciaQLS(strSentenciaUpdate);
        
        
        mostrarDatos();
        clening ();
        
        }else  JOptionPane.showMessageDialog(null, "  No se modificar correctamente");
        {
    
    }
        
        
        
        
        
        
        
        
    
    }//GEN-LAST:event_ModificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
int k = JOptionPane.showConfirmDialog(null, "desea eliminar  ");
        if (k==0) {                  JOptionPane.showMessageDialog(null, " se elimino correctamente"); 
        ClaseCategoriaCRUD objClaseCategoriaCRUD = new ClaseCategoriaCRUD(); //CONEXION BD
        
        ClaseCategoria oCategoria = recuperarDatosGUI();   
        
        String strSentenciaDelete = String.format("DELETE FROM TABCATEGORIA WHERE CODIGO_CATE = %d",oCategoria.getCODIGO());
        
        objClaseCategoriaCRUD.ejecutarSentenciaQLS(strSentenciaDelete);
        
        this.mostrarDatos();
        this.clening();   
        
        }
        else   {
            JOptionPane.showMessageDialog(null, " No elimino correctamente");
        }       
        
            
    }//GEN-LAST:event_eliminarActionPerformed
    
    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed

int k = JOptionPane.showConfirmDialog(null, "desea  crear");
        if (k==0) { JOptionPane.showMessageDialog(null, "se agrego correctamente");

               ClaseCategoriaCRUD objClaseCategoriaCRUD = new ClaseCategoriaCRUD(); //CONEXION BD
        
        ClaseCategoria oCategoria = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("INSERT INTO TABCATEGORIA (ID_CATE,CODIGO_CATE, NOMBRE, SUELDO) VALUES (null,'%s','%s',%s)",oCategoria.getCODIGO(),oCategoria.getNOMBRE(),oCategoria.getSUELDO());
        
        objClaseCategoriaCRUD.ejecutarSentenciaQLS(strSentenciaInsert);
        
        
        mostrarDatos();
        clening ();
      
        } else{
                              JOptionPane.showMessageDialog(null, "No se agrego correctamente");

        } 
        
        
        
        
           
  
       
    }//GEN-LAST:event_CrearActionPerformed

        
    
        public ClaseCategoria recuperarDatosGUI(){
        ClaseCategoria oCategoria = new ClaseCategoria();
        
         oCategoria.setCODIGO(Integer.parseInt(txtCodigo.getText()));
         oCategoria.setNOMBRE((txtNombre.getText()));
         oCategoria.setSUELDO(txtSueldo.getText());

         return oCategoria;
        
    
    }
        
        
        public void mostrarDatos(){
        
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        
        ClaseCategoriaCRUD objClaseCategoriaCRUD = new ClaseCategoriaCRUD(); //CONEXION BD
        
        try {
            ResultSet resultado = objClaseCategoriaCRUD.consultarRegistros("SELECT * FROM TABCATEGORIA");
            
            while (resultado.next()) {
                //System.out.println(resultado.getString("ID"));
                System.out.println(resultado.getString("CODIGO_CATE"));
                System.out.println(resultado.getString("NOMBRE"));
                System.out.println(resultado.getString("SUELDO"));
                
                Object[] oUsuario={resultado.getString("CODIGO_CATE"),resultado.getString("NOMBRE"),resultado.getString("SUELDO")};
                
                modelo.addRow(oUsuario);
                
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
      ClaseVistaHome home = new ClaseVistaHome();
      home.setVisible(true);  
      this.setVisible(false);  
        
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        ClaseVistaEmpleado visEmpleado = new ClaseVistaEmpleado();
        visEmpleado.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         ClaseVistaRegistroNomina visNomina = new ClaseVistaRegistroNomina();
        visNomina.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ClaseVistaContratos visContra = new ClaseVistaContratos();
        visContra.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ClaseVistaComplementos visComple = new ClaseVistaComplementos();
        visComple.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ClaseVistaDeducciones visDedu = new ClaseVistaDeducciones();
        visDedu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        ClaseVistaCalculoSueldo visCalcu = new ClaseVistaCalculoSueldo();
        visCalcu.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ClaseVistaTransacciones visTransa = new ClaseVistaTransacciones();
        visTransa.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped



      // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
      // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyTyped
     // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void tblCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriaMouseClicked
        // TODO add your handling code here:
        
         if (evt.getClickCount()==1) {
            
         JTable receptor = (JTable)evt.getSource();
          
          txtCodigo.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),0));
          txtNombre.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),1));
          txtSueldo.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),2));

          
        }
        
        
        
    }//GEN-LAST:event_tblCategoriaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaseVistaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables

    private static class tablaCategoria {

        private static void setModel(DefaultTableModel modelo) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

       

    }
    }
 

