/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udec.poo.pagodesueldo.vistas.gui;



/**
 *
 * @author JARK
 */
public class ClaseVistaHome extends javax.swing.JFrame {

    /**
     * Creates new form ClaseVistaHome
     */
    public ClaseVistaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnVistaEmpleado = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnVistaDeducciones = new javax.swing.JMenuItem();
        btnVistaComplementos = new javax.swing.JMenuItem();
        btnVistaCategorias = new javax.swing.JMenuItem();
        btnVistaContratos = new javax.swing.JMenuItem();
        btnVistaRNomina = new javax.swing.JMenuItem();
        btnVistaSueldos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnVistaTransacciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema De Nomina");
        setBackground(new java.awt.Color(0, 153, 153));
        setResizable(false);
        setSize(new java.awt.Dimension(950, 580));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK.png"))); // NOI18N

        btnVistaEmpleado.setText("Menu");

        jMenuItem1.setText("Empleados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btnVistaEmpleado.add(jMenuItem1);

        btnVistaDeducciones.setText("Deducciones");
        btnVistaDeducciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaDeduccionesActionPerformed(evt);
            }
        });
        btnVistaEmpleado.add(btnVistaDeducciones);

        btnVistaComplementos.setText("Complementos");
        btnVistaComplementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaComplementosActionPerformed(evt);
            }
        });
        btnVistaEmpleado.add(btnVistaComplementos);

        btnVistaCategorias.setText("Categorias");
        btnVistaCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaCategoriasActionPerformed(evt);
            }
        });
        btnVistaEmpleado.add(btnVistaCategorias);

        btnVistaContratos.setText("Contratos");
        btnVistaContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaContratosActionPerformed(evt);
            }
        });
        btnVistaEmpleado.add(btnVistaContratos);

        btnVistaRNomina.setText("R. Nomina");
        btnVistaRNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaRNominaActionPerformed(evt);
            }
        });
        btnVistaEmpleado.add(btnVistaRNomina);

        jMenuBar1.add(btnVistaEmpleado);

        btnVistaSueldos.setText("Procesos");

        jMenuItem2.setText("C. Sueldos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        btnVistaSueldos.add(jMenuItem2);

        btnVistaTransacciones.setText("Transacciones");
        btnVistaTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaTransaccionesActionPerformed(evt);
            }
        });
        btnVistaSueldos.add(btnVistaTransacciones);

        jMenuBar1.add(btnVistaSueldos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        ClaseVistaEmpleado visEmpleado = new ClaseVistaEmpleado();
        visEmpleado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnVistaComplementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaComplementosActionPerformed
        // TODO add your handling code here:
        ClaseVistaComplementos visComple = new ClaseVistaComplementos();
        visComple.setVisible(true);
       dispose();
        
        
    }//GEN-LAST:event_btnVistaComplementosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ClaseVistaCalculoSueldo visCalcu = new ClaseVistaCalculoSueldo();
        visCalcu.setVisible(true);
        this.setVisible(false);        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnVistaDeduccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaDeduccionesActionPerformed
        // TODO add your handling code here:
        ClaseVistaDeducciones visDedu = new ClaseVistaDeducciones();
        visDedu.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnVistaDeduccionesActionPerformed

    private void btnVistaCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaCategoriasActionPerformed
        // TODO add your handling code here:
        
        ClaseVistaCategoria visCate = new ClaseVistaCategoria();
        visCate.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVistaCategoriasActionPerformed

    private void btnVistaContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaContratosActionPerformed
        // TODO add your handling code here:
        
        ClaseVistaContratos visContra = new ClaseVistaContratos();
        visContra.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnVistaContratosActionPerformed

    private void btnVistaRNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaRNominaActionPerformed
        // TODO add your handling code here:
        
        ClaseVistaRegistroNomina visNomina = new ClaseVistaRegistroNomina();
        visNomina.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnVistaRNominaActionPerformed

    private void btnVistaTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaTransaccionesActionPerformed
        // TODO add your handling code here:
        ClaseVistaTransacciones visTransa = new ClaseVistaTransacciones();
        visTransa.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_btnVistaTransaccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaseVistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaseVistaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnVistaCategorias;
    private javax.swing.JMenuItem btnVistaComplementos;
    private javax.swing.JMenuItem btnVistaContratos;
    private javax.swing.JMenuItem btnVistaDeducciones;
    private javax.swing.JMenu btnVistaEmpleado;
    private javax.swing.JMenuItem btnVistaRNomina;
    private javax.swing.JMenu btnVistaSueldos;
    private javax.swing.JMenuItem btnVistaTransacciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
