/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udec.poo.pagodesueldo.vistas.gui;

import co.edu.udec.poo.pagodesueldo.modelo.crud.ClaseEmpleadoCRUD;
import co.edu.udec.poo.pagodesueldo.poo.modelo.entidades.ClaseEmpleado;
//import co.edu.udec.poo.pagodesueldo.poo.modelo.entidades.ClaseEmpleado;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;





/**
 *
 * @author JARK
 */
public class ClaseVistaEmpleado extends javax.swing.JFrame {
    
    DefaultTableModel modelo;
    
        public ClaseVistaEmpleado() {
        initComponents();
        
        String[] titulos={"NOMBRE", "APELLIDO", "CEDULA", "DIRECCION", "TELEFONO", "ID CATEGORIA", "N.CUENTA","N.CONTRATO"};
        modelo = new DefaultTableModel(null,titulos);
        
        tblEmpleados.setModel(modelo);
        
        mostrarDatos();
        }

        
    void clening (){
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtNcontrato.setText("");
        txtTelefono.setText("");
        txtNcuenta.setText("");
        txtDireccion.setText("");
        txtIdCategoria.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActualizar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNcuenta = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        Crear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtIdCategoria = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNcontrato = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        SE = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        btnActualizar1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnActualizar1.setText("Actualizar");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleados");
        setSize(new java.awt.Dimension(950, 580));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 580));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel1KeyTyped(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Dirreción ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Apellido");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("No. Cuenta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1320, 0));

        tblEmpleados.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Dirreción ", "Telefono", "Id Categoria", "No.cuenta", "No.Contrato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmpleados);
        if (tblEmpleados.getColumnModel().getColumnCount() > 0) {
            tblEmpleados.getColumnModel().getColumn(0).setResizable(false);
            tblEmpleados.getColumnModel().getColumn(1).setResizable(false);
            tblEmpleados.getColumnModel().getColumn(2).setResizable(false);
            tblEmpleados.getColumnModel().getColumn(3).setResizable(false);
            tblEmpleados.getColumnModel().getColumn(4).setResizable(false);
            tblEmpleados.getColumnModel().getColumn(5).setResizable(false);
            tblEmpleados.getColumnModel().getColumn(6).setResizable(false);
            tblEmpleados.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 800, 100));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 120, -1));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 120, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 130, -1));

        txtNcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNcuentaActionPerformed(evt);
            }
        });
        txtNcuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNcuentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 130, -1));

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 120, -1));

        Crear.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/CREARSMALL.png"))); // NOI18N
        Crear.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/CREARSMALL.png"))); // NOI18N
        Crear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/Diseño sin título.png"))); // NOI18N
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        jPanel1.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 100, 60));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Num Contrato");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, 10));

        txtIdCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdCategoriaKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 110, -1));

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 120, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Cedula");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARPE.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARPE.png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/ELIMINARBIG.png"))); // NOI18N
        btnEliminar.setSelected(true);
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 70, 60));
        btnEliminar.getAccessibleContext().setAccessibleDescription("");

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 110, 30));

        Buscar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/pequebuscar.png"))); // NOI18N
        Buscar.setText(" ");
        Buscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/pequebuscar.png"))); // NOI18N
        Buscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/grandebuscar.png"))); // NOI18N
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 70, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        Modificar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARPEQUE.png"))); // NOI18N
        Modificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARPEQUE.png"))); // NOI18N
        Modificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/MODIFICARGRANDE.png"))); // NOI18N
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 100, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel4.setText("EMPLEADOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Crear");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 90, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Eliminar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 90, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Modificar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 90, -1));

        txtNcontrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNcontratoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNcontrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 110, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Id Categoria");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Id Categoria");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        SE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/pagodesueldo/vistas/iconos/NÓMINA JARK (1).png"))); // NOI18N
        jPanel1.add(SE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 540));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Deducciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Complementos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Categorias");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("R. Nomina");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setText("Contratos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem10.setText("Home");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");

        jMenuItem6.setText("C. Sueldos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Transacciones");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 937, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        ClaseVistaTransacciones visTransa = new ClaseVistaTransacciones();
        visTransa.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        ClaseVistaHome home = new ClaseVistaHome();
        home.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
 int k = JOptionPane.showConfirmDialog(null, "dese elimar al usuario");
        if (k==0) {        
        ClaseEmpleadoCRUD objClaseEmpleadoCRUD = new ClaseEmpleadoCRUD(); //CONEXION BD
        
        ClaseEmpleado oEmpleados = recuperarDatosGUI();   
        
        String strSentenciaDelete = String.format("DELETE FROM EMPLEADOS WHERE NUM_CEDULA = %d",oEmpleados.getNUM_CEDULA());
        
        objClaseEmpleadoCRUD.ejecutarSentenciaQLS(strSentenciaDelete);
        
        this.mostrarDatos();
        this.clening();

        } 
if(k!=0){
       JOptionPane.showMessageDialog(null, "no se elimino correctamente"); 
}   
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        ClaseVistaCalculoSueldo visCalcu = new ClaseVistaCalculoSueldo();
        visCalcu.setVisible(true);
        this.setVisible(false); 
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ClaseVistaDeducciones visDedu = new ClaseVistaDeducciones();
        visDedu.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ClaseVistaComplementos visComple = new ClaseVistaComplementos();
        visComple.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ClaseVistaCategoria visCate = new ClaseVistaCategoria();
        visCate.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ClaseVistaRegistroNomina visNomina = new ClaseVistaRegistroNomina();
        visNomina.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         
        ClaseVistaContratos visContra = new ClaseVistaContratos();
        visContra.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
        
        if (evt.getClickCount()==1) {
            
            JTable receptor = (JTable)evt.getSource();
            
          txtNombre.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),0));
          txtApellido.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),1));
          txtCedula.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),2));
          txtDireccion.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),3));
          txtTelefono.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),4));
          txtIdCategoria.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),5));
          txtNcuenta.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),6));
          txtNcontrato.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),7));
          
        }
        
        
        
        

    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed



        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed


    }//GEN-LAST:event_BuscarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped


    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed


    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped


    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed





    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped

    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped

    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNcuentaActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_txtNcuentaActionPerformed

    private void txtNcuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNcuentaKeyTyped

        
        
        
        
    }//GEN-LAST:event_txtNcuentaKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped


        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtIdCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdCategoriaKeyTyped

/*

char Validar=evt.getKeyChar();
        if (Validar<'0'||Validar>'9')evt.consume(); {
            
        }          // TODO add your handling code here:*/
    }//GEN-LAST:event_txtIdCategoriaKeyTyped

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped

        /*
        char Validar=evt.getKeyChar();
        if (Validar<'0'||Validar>'9')evt.consume(); {
            
        } */
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void jPanel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyTyped

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
      int k = JOptionPane.showConfirmDialog(null, "dese agregar al usuario");
        if (k==0) {
          JOptionPane.showMessageDialog(null, "se agrego correctamente");
        
        ClaseEmpleadoCRUD objClaseEmpleadoCRUD = new ClaseEmpleadoCRUD(); //CONEXION BD
        
        ClaseEmpleado oEmpleados = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("INSERT INTO EMPLEADOS(NUM_CEDULA,EMP_NOMBRE, EMP_APELLIDO, TELEFONO, NUM_CUENTA, EMP_DIRECCION,COD_CATEGORIA, NUM_CONTRATO) VALUES (%s, '%s' , '%s', '%s' ,%s, '%s',%s,%s)",oEmpleados.getNUM_CEDULA(),oEmpleados.getEMP_NOMBRE(),oEmpleados.getEMP_APELLIDO(),oEmpleados.getTELEFONO(),oEmpleados.getNUM_CUENTA(),oEmpleados.getEMP_DIRECCION(),oEmpleados.getCOD_CATEGORIA(),oEmpleados.getNUM_CONTRATO());
        
        objClaseEmpleadoCRUD.ejecutarSentenciaQLS(strSentenciaInsert);
        
        
        mostrarDatos();
        clening ();}
     if(k!=0){
       JOptionPane.showMessageDialog(null, "no agrego correctamente"); 
}   
    }//GEN-LAST:event_CrearActionPerformed
    
    public void mostrarDatos(){
        
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        
        ClaseEmpleadoCRUD objClaseEmpleadoCRUD = new ClaseEmpleadoCRUD(); //CONEXION BD
        
        try {
            ResultSet resultado = objClaseEmpleadoCRUD.consultarRegistros("SELECT * FROM EMPLEADOS");
            
            while (resultado.next()) {
                //System.out.println(resultado.getString("ID"));
                System.out.println(resultado.getString("EMP_NOMBRE"));
                System.out.println(resultado.getString("EMP_APELLIDO"));
                System.out.println(resultado.getString("NUM_CEDULA"));
                System.out.println(resultado.getString("EMP_DIRECCION"));
                System.out.println(resultado.getString("TELEFONO"));
                System.out.println(resultado.getString("COD_CATEGORIA"));
                System.out.println(resultado.getString("NUM_CUENTA"));
                System.out.println(resultado.getString("NUM_CONTRATO"));
                
                Object[] oUsuario={resultado.getString("EMP_NOMBRE"),resultado.getString("EMP_APELLIDO"),resultado.getString("NUM_CEDULA"),resultado.getString("EMP_DIRECCION"),resultado.getString("TELEFONO"),resultado.getString("COD_CATEGORIA"),resultado.getString("NUM_CUENTA"),resultado.getString("NUM_CONTRATO")};
                
                modelo.addRow(oUsuario);
                
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    
    
    public ClaseEmpleado recuperarDatosGUI(){
        ClaseEmpleado oEmpleados = new ClaseEmpleado();
        
         oEmpleados.setNUM_CEDULA(Integer.parseInt(txtCedula.getText()));
         oEmpleados.setEMP_NOMBRE(txtNombre.getText());
         oEmpleados.setEMP_APELLIDO(txtApellido.getText());
         oEmpleados.setTELEFONO(txtTelefono.getText());
         oEmpleados.setNUM_CUENTA(Integer.parseInt(txtNcuenta.getText()));
         oEmpleados.setEMP_DIRECCION(txtDireccion.getText());
         oEmpleados.setCOD_CATEGORIA(Integer.parseInt(txtIdCategoria.getText()));
         oEmpleados.setNUM_CONTRATO(Integer.parseInt(txtNcontrato.getText()));
         
         return oEmpleados;
        
    
    }
    
    
    
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        
        int k = JOptionPane.showConfirmDialog(null, "dese modificar al usuario");
        if (k==0) {        
        ClaseEmpleadoCRUD objClaseEmpleadoCRUD = new ClaseEmpleadoCRUD(); //CONEXION BD
        
        ClaseEmpleado oEmpleados = recuperarDatosGUI();
        
        String strSentenciaUpdate = String.format("UPDATE EMPLEADOS SET EMP_NOMBRE='%s',EMP_APELLIDO='%s',TELEFONO='%s',NUM_CUENTA='%s',EMP_DIRECCION='%s',COD_CATEGORIA='%s',NUM_CONTRATO='%s' WHERE NUM_CEDULA='%d'",oEmpleados.getEMP_NOMBRE(),oEmpleados.getEMP_APELLIDO(),oEmpleados.getTELEFONO(),oEmpleados.getNUM_CUENTA(),oEmpleados.getEMP_DIRECCION(),oEmpleados.getCOD_CATEGORIA(),oEmpleados.getNUM_CONTRATO(),oEmpleados.getNUM_CEDULA());
        
        objClaseEmpleadoCRUD.ejecutarSentenciaQLS(strSentenciaUpdate);
        
        
        mostrarDatos();
        clening ();
        

        if(k!=0){
       JOptionPane.showMessageDialog(null, "no se modifico correctamente"); 
}   
      
        
        /*
        int f = JOptionPane.showConfirmDialog(null, "desea modifical asuario");
    
    if(f==0){
        JOptionPane.showMessageDialog(null, "en proceso para inicar la modificación");
      actualizarRegis();
      
    }else{
        JOptionPane.showMessageDialog(null, "Cancelo la modifiación");
        
    }*/

    }//GEN-LAST:event_ModificarActionPerformed
    }
    private void txtNcontratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNcontratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNcontratoActionPerformed

 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel SE;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtNcontrato;
    private javax.swing.JTextField txtNcuenta;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    
}
